### ISSUE TITLE
ElasticCache Redis 캐싱 구현

### ISSUE THREAD

**Issue by le2sky** [prography7th/weather-backend#42]
# 1 . 캐싱 및 메인 컨텐츠 구상

![image](https://user-images.githubusercontent.com/39932141/165734894-3eddc49c-7a60-4853-a7ef-191b170f0832.png)

1. weather-backend에서 cron으로 sqs(메시지 대기열)에 전국 좌표와 매칭되는 지역코드 전달
    -  [x] cron 시간대 정하기
    -  [x] sqs, lambda 연동

3. Lambda는 메시지 대기열을 감시하고 하나씩 처리해서 Redis에 캐싱
    - 람다함수는 기존 Forecast 모듈에서 분리
    - 람다함수에서 메인컨텐츠 분리 로직 필요

redis 자료형
지역코드:20220428 : hash{기존 forecast 반환값 } or string으로 하고 직렬화
지역코드-contents:20220428:  lists[ 가능한 콘텐츠들 ]

**Comment by le2sky** [comment]
@annahxxl  더 괜찮은 방안 생각나면 피드백 부탁할게용

**Comment by annahxxl** [comment]
@le2sky 확인해써~~ 굳굳 😄 👍

**Comment by le2sky** [comment]
악몽의 시작
