### ISSUE TITLE
날씨 정보 요청 실패 지역

### ISSUE THREAD

**Issue by le2sky** [prography7th/weather-backend#64]
- [x] 날씨 정보 요청 실패 지역, 성공 지역 확인 필요
- [x]  중복된 좌표와 빈 좌표 확인 필요
- [x]  격자로 요청하는 거면 좌표변환 모듈이 필요한지 생각 
- [x]  람다 baseDate, baseTime 확인

**Comment by le2sky** [comment]
@annahxxl  한나! 지금 백엔드 서버에서 SQS에 좌표를 날릴때 DMS를 DD로 바꿔서 요청하는데 엑셀 파일 보니깐 격자는 뭐야?
격자로 요청을 하는 거라고 생각하면 되나? 

지금 상태
DB의 DMS 좌표 -> DD 변환 -> DD 좌표 발행 -> 람다에서  기상청 좌표변환모듈 -> 요청

개선
DB의 격자 -> 격자 발행 -> 람다에서 격자로 요청

**Comment by annahxxl** [comment]
@le2sky  격좌로 요청을 보내긴 하는데 보통 구까지만 보면 구마다 겹치긴 하거든? 근데 예를 들면 2개의 다른 행정구역이 같은 좌표를 가지고 있는 경우가 있어서, 개선하려면 이거 고려해야 해! 😢

추가로, 지금 보니까 동이 달라지면 행정 구역 코드도 달라져성..

<img width="801" alt="스크린샷 2022-05-26 11 22 16" src="https://user-images.githubusercontent.com/76666857/170402428-aa84686b-229d-4b67-9e7a-7e34fcb7f5f7.png">

**Comment by annahxxl** [comment]
@le2sky 하늘아!!! 지금 보니깐 구마다 행정구역 코드 앞자리 4자리가 같긴 한데 이거 이용해서 개선해 볼까?? 그럼 좌표 겹치긴 해도 행정구역 코드 기준이니까 가능할 것 같아! 대신 그 앞자리 4개 필터링은 너 쪽에서 해줘야 할 듯! 유저 쪽 행정구역 조회할 때 문제 생길 수 있어서, 그리고 개선하게 되면 유저 쪽 코드도 손보긴 해야 해!
.
.
.
다시보니깐 앞에 4자리 같아도 xy좌표 다를때도 있네.. 이 방법 안될 것 같아..ㅋㅋㅋㅋ
